#!/bin/bash

#apt list --installed | grep libopengl-dev
#apt list --installed | grep libglew-dev
#apt list --installed | grep libglfw3-dev
#apt list --installed | grep libgtest-dev


if dpkg -s libglew-dev >/dev/null 2>&1; then
    echo "glew is installed"
else
    echo "glew is not installed..."
    echo "installing glew:"
    sudo apt install libglew-dev  

fi


if dpkg -s libopengl-dev >/dev/null 2>&1; then
    echo "OpenGL is installed"
else
    echo "OpenGL is not installed..."
    echo "installing OpenGL"
    sudo apt install libopengl-dev
fi


if dpkg -s libglfw3-dev >/dev/null 2>&1; then
    echo "glfw is installed"
else
    echo "glfw is not installed..."
    echo "installing glfw"
    sudo apt install libglfw3-dev
fi



if dpkg -s libgtest-dev >/dev/null 2>&1; then
    echo "gtest is installed"
else
    echo "gtest is not installed..."
    echo "installing gtest"
    sudo apt install libgtest-dev
fi

#install imgui and glfw

#cd libs && rm -r /libs/*
#mkdir /libs/imgui && libs/glfw

git clone -b v1.92.7 https://github.com/ocornut/imgui.git libs/imgui
#git clone -b 3.3.10 https://github.com/glfw/glfw.git libs/glfw
